config/routes.rb
RottenMangos::Application.routes.draw do

  get "reviews/new"
  get "reviews/create"
  resources :movies do
    resources :reviews, only: [:new, :create]
  end
  root to: 'movies#index'
  
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

    namespace :admin do
      resources :users do
        resources :spoofs, only: [:create, :destroy]
      end
  end

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, numericality: { only_integer: true }
  validates :description, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_past
  has_many :reviews

  mount_uploader :image, AvatarUploader

  scope :search, -> (title_director) { where("title LIKE ? OR director LIKE ?", title_director, title_director) }
  scope :under_90, -> { where("runtime_in_minutes < 90") }
  scope :over_120, -> { where("runtime_in_minutes > 120") }
  scope :between_90_and_120, -> { where("runtime_in_minutes BETWEEN 90 AND 120") }

  def review_average
   reviews.size != 0 ? reviews.sum(:rating_out_of_ten)/reviews.size : "N/A"
  end


  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, "Should be in the past!") if release_date > Date.today
    end
  end

end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  
  validates :user, presence: true
  validates :movie, presence: true
  validates :text, presence: true
  validates :rating_out_of_ten, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  has_secure_password

  def full_name
    "#{firstname} #{lastname}"
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  before_filter :restrict_admin_access

  def index
    @users = User.order(:id).page(params[:page]).per(5)
    render :index
  end

  def new

    @user = User.new

  end

  def create

    @user = User.new(admin_params)
    if @user.save
      redirect_to admin_users_path, notice: "#{@user.full_name} was successfully created!"
    else
      render :new
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(admin_params)
      redirect_to admin_users_path, notice: "#{@user.firstname}'s info has been updated!"
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
      if @user.destroy
        # Tell the UserMailer to send a welcome email after save 
        UserMailer.delete_email(@user).deliver
        redirect_to admin_users_path, notice: "#{@user.full_name} has been deleted!"
      else
        render :show
      end
  end


  protected

  def restrict_admin_access

    if !current_user || (current_user.admin == nil || current_user.admin == false)
      flash[:alert] = "You must be an admin."
      redirect_to movies_path
    end

  end

  def admin_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation, :admin)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access

    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end

  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


  def index

    @movies = Movie.all
    @movies = @movies.search(params[:title_director]) if params[:title_director].present?
    @prev_choice = params[:runtime] if params[:runtime]
    @movies = @movies.under_90 if params[:runtime] == "a"
    @movies = @movies.between_90_and_120 if params[:runtime] == "b"
    @movies = @movies.over_120 if params[:runtime] == "c"
    # if params[:runtime].present?
    #   case params[:runtime]
    #   when "a"
    #    @movies = Movie.under_90
    #   when "b"
    #    @movies = Movie.between_90_and_120
    #   when "c"
    #    @movies = Movie.over_120
    #   end
    # end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was added to the list of movies!"
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movies_path, notice: "#{@movie.title} has been updated!"
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end


  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :poster_image_url, :description, :image
      )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_filter :load_movie
  before_filter :restrict_access
  
  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Your review was added successfully"
    else
      render :new
    end
  end

  protected

  def load_movie
    @movie = Movie.find(params[:movie_id])
  end
  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Invalid email or password..."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Thanks for visiting!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  protected

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :password, :password_confirmation)
  end

  def is_admin?
    @user.admin == true
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
  
  # def which_time_frame(choice=nil)
  #   case choice
  #     when a
  #      < 90
  #     when b
  #      90..120
  #     when c
  #      > 120
  #   end
  # end

end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<%= form_for [:admin, @user], html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented this user from being submitted:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
    <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :admin, "Admin" %>
    <%= f.select :admin, [['Active', true], ['Inactive', false], ['None', nil]] %>
  </div> 
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/index.html.erb
<h1>List of all Users</h1>
<% @users.each do |user| %>
  <br><%= link_to user.full_name, admin_user_path(user) %>
  <%= link_to "Delete", admin_user_path(user), :method => :delete, :"data-confirm" => "Your sure?" %>
<% end %>
<hr>
  <%= link_to "New admin account", new_admin_user_path %>
<hr>
<%= paginate @users %>

app/views/admin/users/new.html.erb
<%= form_for [:admin, @user], html: { multipart: true } do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented this user from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
    <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :admin, "Admin" %>
    <%= f.select :admin, [['Active', true], ['Inactive', false], ['None', nil]] %>
  </div> 
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/admin/users/show.html.erb
<h1>Name: <%= @user.full_name %></h1>
<hr>
<h3>Email: <%= @user.email %></h3><br>
<h3>Admin Status: <%= @user.admin %></h3>
[<%= link_to "Edit User", edit_admin_user_path %>]
[<%= link_to "Delete", admin_user_path(@user), :method => :delete, :"data-confirm" => "Your sure?" %>]

app/views/layouts/_footer.html.erb
<footer>
  <small>
    <% if current_user && current_user.admin == true %>
      Signed in as <%= current_user.full_name %> [<%= link_to "Log out", session_path("current"), method: :delete %>][<%= link_to "Admin page", admin_users_path %>]
    <% elsif current_user %> 
      Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>)
    <% else %>
    <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RottenMangos</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value) %>
  <% end %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true } do |f| %>
  <% if @movie.errors.any? %>
    <div>
      <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
      <ul>
        <% @movie.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
      </ul>
    </div>
    <% end %>
  <div>
    <%= f.label 'title' %><br>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.label 'director' %><br>
    <%= f.text_field "director" %>
  </div>
  <div>
    <%= f.label 'runtime_in_minutes' %><br>
    <%= f.number_field "runtime_in_minutes" %>
  </div>
  <div>
    <%= f.label 'description' %><br>
    <%= f.text_area "description" %>
  </div>
  <div>
    <%= f.label 'image' %><br>
    <%= f.file_field "image" %>
  </div>
  <div>
    <%= f.label 'release_date' %><br>
    <%= f.date_field "release_date" %>
  </div>
  <div>
    <%= f.submit "Save" %><br>
<% end %>

app/views/movies/_header.html.erb
<h1><%= link_to "Rotten Mangoes", root_path %></h1>
<hr>
  

    

app/views/movies/_movie.html.erb
<% @movies.each do |movie| %>
  <%= image_tag movie.image.url %>
  <h2><%= link_to movie.title, movie_path(movie) %></h2>
  <h3><%= formatted_date(movie.release_date) %></h3>
  <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
  <p><%= movie.description %></p>
  <hr>
<% end %>

app/views/movies/edit.html.erb
<%= render 'header' %>
<%= link_to "Back to movie", movie_path %>
<h1>Edit the movie</h1>
<hr>
<%= render 'form' %>
<%= link_to "Delete", movie_path(@movie), :method => :delete, :"data-confirm" => "Your sure?" %>

app/views/movies/index.html.erb
  <%= render 'header' %>
  <%= link_to "Submit a movie!", new_movie_path %><br>
  <%= form_tag movies_path, :method => 'get' do %>
    <p>
      <%= text_field_tag :title_director, params[:title_director], placeholder: "Title or Director" %>
      <%= select_tag :runtime, options_for_select([['Less than 90 Minutes', "a"], ['Between 90 and 120 Minutes', "b"], ['Greater than 120 Minutes', "c"]], @prev_choice), :include_blank => true %>
      <%= submit_tag "Search" %>
    </p>
  <% end %>
  <%= render 'movie' %>

app/views/movies/new.html.erb
<h1>Post a new movie</h1>
<%= render 'header' %>
<hr>
<%= render 'form' %>
<%= link_to "Home", movies_path %>

app/views/movies/show.html.erb
<%= render 'header' %>
<h1>EDIT: <%= link_to @movie.title, edit_movie_path %></h1>
<%= image_tag(@movie.image.url) %><br>
<h2><%= formatted_date(@movie.release_date) %></h2>
<h3>Director: <%= @movie.director %> | <%= @movie.runtime_in_minutes %></h3>
<% if @movie.review_average != "N/A" %><br>
<%= @movie.review_average %>/10 average rating
<% end %>
<p><%= @movie.description %></p>

<hr>

<h3>Reviews of <em><%= @movie.title %></em></h3>
  <% if current_user %>
    <% @movie.reviews.each do |review| %>
      <p><%= review.text %></p>
      <p><%= review.rating_out_of_ten %>/10</p>
      <% if current_user == review.user %>
      <small>- <%= review.user.full_name %> </small>
      <% else %>
      <small>- <%= link_to review.user.full_name, user_path(review.user) %></small><br/>
      <% end %>
    <% end %>
    <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
  <% else %>
    <p>Please <% link_to "Log In", new_session_path %> to see the reviews and add your own </p>
  <% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

<h2>Write a review of <em><%= @movie.title %></em></h2>

<%= form_for([@movie, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div>
      <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
      <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div>
    <%= f.label :rating_out_of_ten %><br>
    <%= f.number_field :rating_out_of_ten %>
  </div>
  <div><%= f.submit "Submit" %></div>
  <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>New user signup!</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div>
      <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :firstname, "First Name" %><br>
    <%= f.text_field :firstname %>
  </div>
  <div>
    <%= f.label :lastname, "Last Name" %><br>
    <%= f.text_field :lastname %>
  </div>
  <div>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div><%= f.submit "Submit" %></div>
<% end %>

app/views/users/show.html.erb
<h1>Name: <%= @user.full_name %></h1>
<hr>
<h3>Email: <%= @user.email %></h3><br>
<% @user.reviews.each do |review| %>
  <%= link_to review.movie.title, movie_path(review.movie) %>
<p><%= review.text %></p>
<% end %>